specVersion: "0.2.0"

name: "Frontier EVM Starter Project"
version: "1.0.0"
description: "A basic Frontier EVM example project with an event and call handler. Read more about this at https://doc.subquery.network/create/frontier/"
repository: "https://github.com/cheesekon/tutorials-frontier-evm-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: 'wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5'
  genesisHash: '0xd0599a36a2fb1e958d74c51c439b63f5ee91b7c107940caec1ec78958c2d3422'
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 131756
    processor:
      file: './node_modules/@subql/contract-processors/dist/frontierEvm.js'
      options:
        # Must be a key of assets
        abi: contract
        ## The contract that emitted the event
        address: '0x8d15Db7450508eF9486d928162D72FB9128d658b'
    assets:
      contract:
        file: './contract.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleList
          kind: substrate/FrontierEvmCall
          filter:
            function: list(uint256,address)

      #   - handler: handleListEvent
      #     kind: substrate/FrontierEvmEvent
      #     filter:
      #       topics:
      #         - Listed(address from,address to, uint256 sopo_id, uint256 nft_id, address nft_programe_address)

        # - handler: handleListAndSellEvent
        #   kind: substrate/FrontierEvmEvent
        #   filter:
        #     topics:
        #       - Listandforsell(address indexed from, address indexed to, uint256 sopo_id, uint256 nft_id, address nft_programe_address, uint256 price)

        # - handler: handleForsellEvent
        #   kind: substrate/FrontierEvmEvent
        #   filter:
        #     topics:
        #       - Forsell(uint256 sopo_id,uint256 price)
        # - handler: handleNewOfferEvent
        #   kind: substrate/FrontierEvmEvent
        #   filter:
        #     topics:
        #       - Newoffer(address from,address to,uint256 sopo_id,uint256 price)
        # - handler: handleWithdrawEvent
        #   kind: substrate/FrontierEvmEvent
        #   filter:
        #     topics:
        #       - Withdraw(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address,uint32 withdrawout_at)
        # - handler: handleSelledEvent
        #   kind: substrate/FrontierEvmEvent
        #   filter:
        #     topics:
        #       - Selled(address from,address to,uint256 sopo_id,uint32 selled_at,uint256 nft_id,address nft_programe_address,address owner)


            ## The function can either be the method fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            # function: approve(address,uint256)
        # - handler: handleFrontierEvmCall
        #   kind: substrate/FrontierEvmCall
        #   filter:
        #     ## The function can either be the method fragment or signature
        #     # function: '0x095ea7b3'
        #     # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
        #     # function: approve(address,uint256)
        #     function: approve(address to,uint256 value)
        #     ## The transaction sender
        #     from: '0x6bd193ee6d2104f14f94e2ca6efefae561a4334b'


